<?xml version="1.0"?>
<package format="3">
  <name>mobile_robco_description</name>
  <version>0.0.1</version>
  <description>The mobile_robco_description package</description>
  <maintainer email="julian.hoffmann@aiina-robotics.com">Julian Hoffmann</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>xacro</depend>
  <depend>rviz2</depend>
  <depend>robot_state_publisher</depend>
  <depend>joint_state_publisher</depend>
  <depend>joint_state_publisher_gui</depend>
  <depend>ros_gz_sim</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <exec_depend>robot_localization</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
